# Generated by Django 4.1.4 on 2022-12-21 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projectApp", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="category",
            options={"verbose_name": "Category", "verbose_name_plural": "Categories"},
        ),
        migrations.AlterModelOptions(
            name="items",
            options={"verbose_name": "Item", "verbose_name_plural": "Items"},
        ),
        migrations.AddField(
            model_name="category",
            name="slug",
            field=models.SlugField(null=True),
        ),
        migrations.AddField(
            model_name="items",
            name="slug",
            field=models.SlugField(null=True),
        ),
    ]
