# Generated by Django 4.1.4 on 2022-12-22 01:23

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("projectApp", "0002_alter_category_options_alter_items_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="items",
            name="description",
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
