# Generated by Django 4.1.4 on 2022-12-25 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projectApp", "0005_items_count_item"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="items",
            name="count_item",
        ),
        migrations.AddField(
            model_name="cart",
            name="count_item",
            field=models.IntegerField(default=1),
        ),
    ]
