# Generated by Django 4.1.4 on 2022-12-26 01:30

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("projectApp", "0007_rename_favourites_favorites"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Favorites",
            new_name="Favourites",
        ),
    ]
